#!/usr/bin/env php
<?php

include('functions.php');

silentReq('DELETE', '/banking');

waitReq('GET', '/_all_dbs');
waitForInput();

waitReq('PUT', '/banking');
waitForInput();

waitReq('POST', '/banking/', ['_id' => 'julius-beckmann', 'type' => 'account', 'name' => 'Julius Bekmann']);
waitForInput();

$data = waitReq('GET', '/banking/julius-beckmann');
waitForInput();

waitReq('PUT', '/banking/julius-beckmann', ['type' => 'account', 'name' => 'Julius Beckmann']);
waitForInput();

waitReq('PUT', '/banking/julius-beckmann', ['type' => 'account', 'name' => 'Julius Beckmann', '_rev' => $data['_rev']]);
waitForInput();

$data = waitReq('GET', '/banking/julius-beckmann?revs_info=true');
waitForInput();

$data = waitReq('GET', '/banking/julius-beckmann?rev='.$data["_revs_info"][1]['rev']);
waitForInput();


waitReq('POST', '/banking/', ['_id' => 'bill-gates', 'type' => 'account', 'name' => 'Bill Gates']);
waitForInput();


waitReq('POST', '/banking/', ['type' => 'booking', 'owner' => 'julius-beckmann', 'value' => 100]);
waitForInput();

waitReq('POST', '/banking/', ['type' => 'booking', 'owner' => 'bill-gates', 'value' => 100000]);
waitForInput();
