#!/usr/bin/env php
<?php

include('functions.php');

$balanceByAccountJs = 'function(doc) {
  if(\'booking\' === doc.type) {
    emit(doc.owner, doc.value)
  }
}';

$data = silentReq('GET', '/banking/_design/balance');
if(isset($data['_rev'])) {
  silentReq('DELETE', '/banking/_design/balance?rev='.$data['_rev']);
}

waitReq('PUT', '/banking/_design/balance', ['id' => '_design/balance', 
'views' => [
'byAccount' => ['map' => $balanceByAccountJs, 'reduce' => '_sum']

]]);
waitForInput();

waitReq('GET', '/banking/_design/balance/_view/byAccount');
waitForInput();

waitReq('GET', '/banking/_design/balance/_view/byAccount?group_level=1');
waitForInput();
